-- ============================================================
-- Tahap 1: ganti tabel profile lama (skema id bigint + kolom
-- password) dengan skema role-based, plus activity log admin.
--
-- Hanya menyentuh tabel profile (lama, kosong) dan membuat dua
-- objek baru. Tabel projects / skills / pesan_kontak tidak
-- diubah baik data maupun policy.
-- ============================================================

-- (1) Buang tabel profile lama
drop table if exists public.profile;

-- (2) Tabel profile baru
create table public.profile (
  id         uuid primary key references auth.users(id) on delete cascade,
  username   text not null,
  role       text not null default 'admin' check (role in ('admin','editor')),
  created_at timestamptz not null default now()
);
comment on table public.profile is 'Role admin/editor. 1 baris = 1 auth user.';
alter table public.profile enable row level security;

-- (3) Fungsi is_admin()  (harus ada sebelum policy yang memakainya)
-- security definer supaya policy di profile tidak memanggil dirinya
-- sendiri secara rekursif. search_path dikunci supaya auth.uid()
-- tidak bisa di-hijack lewat objek di search path.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profile
    where id = (select auth.uid()) and role = 'admin'
  );
$$;
comment on function public.is_admin() is 'True kalau user yang login punya role admin.';

-- (4) Policy profile
-- User biasa hanya boleh mengedit baris sendiri, dan role-nya
-- terkunci di 'editor' supaya tidak bisa menaikkan role sendiri.
-- Naik role hanya lewat jalur admin.
create policy "profile_select_own_or_admin" on public.profile
  for select to authenticated
  using (id = (select auth.uid()) or public.is_admin());

create policy "profile_insert_own" on public.profile
  for insert to authenticated
  with check (id = (select auth.uid()) and role = 'editor');

create policy "profile_update_own" on public.profile
  for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()) and role = 'editor');

create policy "profile_update_by_admin" on public.profile
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- (5) Tabel admin_activity
create table public.admin_activity (
  id            bigint generated by default as identity primary key,
  user_id       uuid references auth.users(id) on delete set null,
  action        text not null check (action in ('create','update','delete','login')),
  project_title text,
  created_at    timestamptz not null default now()
);
comment on table public.admin_activity is 'Log aktivitas admin (create/update/delete/login).';
alter table public.admin_activity enable row level security;

create policy "admin_activity_select_admin" on public.admin_activity
  for select to authenticated using (public.is_admin());

create policy "admin_activity_insert_admin" on public.admin_activity
  for insert to authenticated with check (public.is_admin());

-- (6) Seed role admin untuk user yang sudah ada
insert into public.profile (id, username, role)
select id, 'desvitaputri', 'admin'
from auth.users
where email = 'desvitaputri27@gmail.com'
on conflict (id) do nothing;
